version: "3.8"

services:
  backend:
    build: ./backend
    image: fastapi:v1
    container_name: fastapi_c
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    image: react:v1
    container_name: react_c
    ports:
      - "5173:5173"
